version: '3'
services:
  haproxy:
    image: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  redis1:
    image: redis
    ports:
      - '6379:6379'
  redis2:
    command: redis-server --slaveof redis1 6379
    image: redis
    ports:
      - '6380:6379'
  app:
    build: .
    environment:
      REDIS_HOST: haproxy
    ports:
      - "3000:3000"
    volumes:
      - .:/app
