version: '3'
services:
  haproxy:
    depends_on:
      - redis1
      - redis2
    image: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  redis1:
    image: redis
    ports:
      - '6379:6379'
  redis2:
    command: redis-server --slaveof redis1 6379
    image: redis
    ports:
      - '6380:6379'
  redis-sentinel:
    entrypoint: bash -c 'cp /etc/redis/sentinel.conf.orig /etc/redis/sentinel.conf && redis-sentinel /etc/redis/sentinel.conf'
    depends_on:
      - redis1
      - redis2
    image: redis
    ports:
      - '26379:26379'
    volumes:
      - ./sentinel.conf:/etc/redis/sentinel.conf.orig
  app:
    build: .
    environment:
      RAILS_MAX_THREADS: 1
      REDIS_HOST: haproxy
    ports:
      - "3000:3000"
    volumes:
      - .:/app
