default: &default
  adapter: mysql2
  database: app
  host: <%= ENV.fetch('MYSQL_HOST', 'localhost') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD', '') %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  timeout: 5000
  username: <%= ENV.fetch('MYSQL_USERNAME', 'app') %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
